# Generated by Sterling SDK Generator — test suite
# Task Manager API v0.2.0

"""Tests for TaskmanagerSdkClient — verifies URL construction, HTTP methods, and error handling."""

import asyncio
from typing import Any
from unittest.mock import AsyncMock, patch, MagicMock

import sys
import os

# Add src to path so we can import the generated client
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from vers_sdk.client import TaskmanagerSdkClient
from vers_sdk.errors import APIError, BadRequestError, NotFoundError, InternalServerError


# ── Helpers ──────────────────────────────────────────────────────────────


class FakeResponse:
    """Minimal httpx.Response stand-in for unit tests."""

    def __init__(self, status_code: int = 200, json_body: Any = None) -> None:
        self.status_code = status_code
        self._json = json_body or {}
        self.headers: dict[str, str] = {"content-type": "application/json"}
        self.text = ""
        self.is_success = 200 <= status_code < 300

    def json(self) -> Any:
        return self._json


captured: dict[str, Any] = {}


def make_client() -> TaskmanagerSdkClient:
    c = TaskmanagerSdkClient(base_url="http://localhost:9999", api_key="test-key", max_retries=0)
    return c


def make_mock(status: int = 200, body: Any = None) -> AsyncMock:
    """Return an AsyncMock that records calls and returns a FakeResponse."""

    async def _request(method: str, path: str, **kwargs: Any) -> FakeResponse:
        captured["method"] = method
        captured["path"] = path
        captured["kwargs"] = kwargs
        resp = FakeResponse(status, body)
        if not resp.is_success:
            raise APIError.generate(status=status, body=body, message=None, headers={})
        return resp

    mock = AsyncMock(side_effect=_request)
    return mock


# ── Operation tests ──────────────────────────────────────────────────────


def run(coro: Any) -> Any:
    return asyncio.get_event_loop().run_until_complete(coro)


def test_list_tasks() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_tasks())
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_create_task() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.create_task({}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_get_task() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.get_task("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_delete_task() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.delete_task("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "DELETE", f"expected DELETE, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_update_task() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.update_task("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "PATCH", f"expected PATCH, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_complete_task() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.complete_task("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"


# ── Error handling tests ─────────────────────────────────────────────────

def test_error_400() -> None:
    c = make_client()
    c._request = make_mock(400, {"message": "bad"})  # type: ignore[assignment]
    try:
        run(c.list_tasks())
        assert False, "should have raised"
    except BadRequestError:
        pass


def test_error_404() -> None:
    c = make_client()
    c._request = make_mock(404, {"message": "not found"})  # type: ignore[assignment]
    try:
        run(c.list_tasks())
        assert False, "should have raised"
    except NotFoundError:
        pass


def test_error_500() -> None:
    c = make_client()
    c._request = make_mock(500, {"message": "server"})  # type: ignore[assignment]
    try:
        run(c.list_tasks())
        assert False, "should have raised"
    except InternalServerError:
        pass


# ── Main runner ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    import inspect

    tests = [(name, obj) for name, obj in globals().items() if name.startswith("test_") and inspect.isfunction(obj)]
    passed = failed = 0
    for name, fn in tests:
        try:
            fn()
            passed += 1
            print(f"  ✓ {name}")
        except Exception as exc:
            failed += 1
            print(f"  ✗ {name}: {exc}")
    print(f"\n{passed} passed, {failed} failed")
    if failed:
        sys.exit(1)
