# Generated by Sterling SDK Generator
# Task Manager API v0.2.0

import asyncio
import calendar
import email.utils
import logging
import os
import random
import time as _time
import uuid
from dataclasses import dataclass, field
from typing import Any, Optional

import httpx

from .errors import APIError, APIConnectionError
from .models import *  # noqa: F403


@dataclass
class RequestOptions:
    """Per-request options that override client defaults."""

    #: Additional headers to send with the request.
    #: Set a header to None to remove it.
    headers: dict[str, str | None] | None = None

    #: Request timeout in seconds. Overrides the client-level timeout.
    timeout: float | None = None

logger = logging.getLogger("vers_sdk")

_LOG_LEVEL_MAP = {
    "debug": logging.DEBUG,
    "info": logging.INFO,
    "warn": logging.WARNING,
    "error": logging.ERROR,
    "off": logging.CRITICAL + 1,
}


def _configure_logger() -> None:
    env_level = os.environ.get("VERS_LOG", "warn").lower()
    level = _LOG_LEVEL_MAP.get(env_level, logging.WARNING)
    logger.setLevel(level)
    if not logger.handlers:
        handler = logging.StreamHandler()
        handler.setFormatter(logging.Formatter("%(asctime)s [vers_sdk %(levelname)s] %(message)s"))
        logger.addHandler(handler)


_configure_logger()


# Status codes that are retryable even though they are 4xx
RETRYABLE_STATUS_CODES = {408, 409, 429}


def _is_retryable_status(status: int) -> bool:
    return status >= 500 or status in RETRYABLE_STATUS_CODES


def _retry_delay(attempt: int) -> float:
    base = 0.5 * (2 ** attempt)
    jitter = random.random() * base * 0.25
    return base + jitter


def _parse_retry_after(header_value: Optional[str]) -> Optional[float]:
    if header_value is None:
        return None
    try:
        delay = float(header_value)
        return min(max(delay, 0.0), 60.0)
    except (ValueError, OverflowError):
        pass
    parsed = email.utils.parsedate(header_value)
    if parsed is not None:
        retry_time = calendar.timegm(parsed)
        delay = retry_time - _time.time()
        return min(max(delay, 0.0), 60.0)
    return None


class TaskmanagerSdkClient:
    """Client for Task Manager API"""

    def __init__(
        self,
        base_url: Optional[str] = None,
        api_key: Optional[str] = None,
        headers: Optional[dict[str, str | None]] = None,
        max_retries: int = 2,
        timeout: float = 30.0,
        http_client: Optional[httpx.AsyncClient] = None,
    ):
        self.base_url = base_url or os.environ.get("VERS_BASE_URL", "http://localhost:8080")
        self.api_key = api_key or os.environ.get("VERS_API_KEY")
        self.max_retries = max_retries
        self.timeout = timeout
        self._custom_headers: dict[str, str | None] = headers or {}
        if http_client is not None:
            self._client = http_client
        else:
            import platform as _platform
            default_headers: dict[str, str] = {
                "User-Agent": f"taskmanager-sdk/0.2.0 python/{_platform.python_version()} {_platform.system().lower()}/{_platform.machine()}",
            }
            if self.api_key:
                default_headers["Authorization"] = f"Bearer {self.api_key}"
            merged = self._merge_headers(default_headers, self._custom_headers)
            self._client = httpx.AsyncClient(
                base_url=self.base_url,
                headers=merged,
                timeout=self.timeout,
            )

    @staticmethod
    def _merge_headers(*sources: Optional[dict[str, str | None]]) -> dict[str, str]:
        """Merge header dicts. Later sources override earlier ones (case-insensitive).
        A ``None`` value removes the header."""
        merged: dict[str, str] = {}
        for source in sources:
            if source is None:
                continue
            for key, value in source.items():
                if value is None:
                    # Remove header (case-insensitive)
                    merged = {
                        k: v for k, v in merged.items()
                        if k.lower() != key.lower()
                    }
                else:
                    merged[key] = value
        return merged

    def _check_response(self, response: httpx.Response) -> None:
        if response.is_success:
            return
        body: Any = None
        message: str | None = None
        ct = response.headers.get("content-type", "")
        if "application/json" in ct:
            try:
                body = response.json()
            except Exception:
                message = response.text
        else:
            message = response.text
        headers = dict(response.headers)
        raise APIError.generate(
            status=response.status_code,
            body=body,
            message=message,
            headers=headers,
        )

    async def _request(self, method: str, path: str, options: RequestOptions | None = None, **kwargs: Any) -> httpx.Response:
        logger.debug("request: %s %s", method, path)

        req_headers: dict[str, str] = kwargs.pop("headers", {})
        if method.upper() in ("POST", "PUT", "PATCH", "DELETE"):
            req_headers["X-Idempotency-Key"] = str(uuid.uuid4())
        # Apply per-request header overrides
        if options and options.headers:
            for k, v in options.headers.items():
                if v is None:
                    req_headers.pop(k, None)
                else:
                    req_headers[k] = v
        if req_headers:
            kwargs["headers"] = req_headers
        effective_timeout = options.timeout if options and options.timeout is not None else None

        last_exc: Optional[Exception] = None
        retry_after_used = False
        for attempt in range(self.max_retries + 1):
            if attempt > 0 and not retry_after_used:
                logger.info("retry attempt %d/%d for %s %s", attempt, self.max_retries, method, path)
                await asyncio.sleep(_retry_delay(attempt - 1))
            retry_after_used = False
            try:
                req_kwargs = dict(kwargs)
                if effective_timeout is not None:
                    req_kwargs["timeout"] = effective_timeout
                response = await self._client.request(method, path, **req_kwargs)
                # Remove headers that were set to None
                logger.debug("response: %d for %s %s", response.status_code, method, path)
                if _is_retryable_status(response.status_code) and attempt < self.max_retries:
                    ra_delay = _parse_retry_after(response.headers.get("retry-after"))
                    if ra_delay is not None:
                        retry_after_used = True
                        logger.info("retry attempt %d/%d for %s %s (retry-after: %.1fs)", attempt + 1, self.max_retries, method, path, ra_delay)
                        await asyncio.sleep(ra_delay)
                    last_exc = Exception(f"HTTP {response.status_code}")
                    continue
                self._check_response(response)
                return response
            except APIError:
                raise
            except (httpx.ConnectError, httpx.TimeoutException) as exc:
                logger.error("connection error: %s %s - %s", method, path, exc)
                if attempt == self.max_retries:
                    raise APIConnectionError(cause=exc) from exc
                last_exc = exc
        raise last_exc  # type: ignore[misc]

    async def list_tasks(self, params: ListTasksParams | None = None, options: RequestOptions | None = None) -> TaskListResponse:
        """List all tasks"""
        path = "/api/tasks"
        query: dict[str, Any] = {}
        if params is not None:
            if params.status is not None:
                query["status"] = params.status
            if params.limit is not None:
                query["limit"] = params.limit
        resp = await self._request("GET", path, options, params=query)
        if not resp.content:
            return {}
        return resp.json()

    async def create_task(self, body: dict[str, Any], options: RequestOptions | None = None) -> Task:
        """Create a new task"""
        path = "/api/tasks"
        resp = await self._request("POST", path, options, json=body)
        if not resp.content:
            return {}
        return resp.json()

    async def get_task(self, task_id: str, options: RequestOptions | None = None) -> Task:
        """Get a task by ID"""
        path = f"/api/tasks/{task_id}"
        resp = await self._request("GET", path, options)
        if not resp.content:
            return {}
        return resp.json()

    async def delete_task(self, task_id: str, options: RequestOptions | None = None) -> Any:
        """Delete a task"""
        path = f"/api/tasks/{task_id}"
        resp = await self._request("DELETE", path, options)
        if not resp.content:
            return {}
        return resp.json()

    async def update_task(self, task_id: str, body: dict[str, Any], options: RequestOptions | None = None) -> Task:
        """Update a task"""
        path = f"/api/tasks/{task_id}"
        resp = await self._request("PATCH", path, options, json=body)
        if not resp.content:
            return {}
        return resp.json()

    async def complete_task(self, task_id: str, body: dict[str, Any] | None = None, options: RequestOptions | None = None) -> Task:
        """Mark a task as done"""
        path = f"/api/tasks/{task_id}/complete"
        resp = await self._request("POST", path, options, json=body)
        if not resp.content:
            return {}
        return resp.json()

    async def close(self) -> None:
        await self._client.aclose()

    async def __aenter__(self) -> "TaskmanagerSdkClient":
        return self

    async def __aexit__(self, *args: Any) -> None:
        await self.close()
