# Generated by Sterling SDK Generator
# Task Manager API v0.2.0

from __future__ import annotations

from typing import Any, Optional


class VersSDKError(Exception):
    """Base error class for the TaskmanagerSdk SDK."""
    pass


class APIError(VersSDKError):
    """Error returned when the API responds with a non-success status code."""

    status: int | None
    headers: dict[str, str] | None
    body: Any

    def __init__(
        self,
        status: int | None,
        body: Any = None,
        message: str | None = None,
        headers: dict[str, str] | None = None,
    ) -> None:
        self.status = status
        self.headers = headers
        self.body = body
        super().__init__(self._make_message(status, body, message))

    @staticmethod
    def _make_message(status: int | None, body: Any, message: str | None) -> str:
        msg = None
        if isinstance(body, dict) and "message" in body:
            msg = body["message"] if isinstance(body["message"], str) else str(body["message"])
        elif body is not None:
            msg = str(body)
        elif message is not None:
            msg = message

        if status and msg:
            return f"{status} {msg}"
        if status:
            return f"{status} status code (no body)"
        if msg:
            return msg
        return "(no status code or body)"

    @property
    def error_message(self) -> str:
        """Extract the human-readable error message from the response.

        Looks for an ``error`` or ``message`` field in the JSON error body,
        or falls back to the raw error text.
        """
        if isinstance(self.body, dict):
            if "error" in self.body and isinstance(self.body["error"], str):
                return self.body["error"]
            if "message" in self.body and isinstance(self.body["message"], str):
                return self.body["message"]
        return str(self)

    @classmethod
    def generate(
        cls,
        status: int | None,
        body: Any = None,
        message: str | None = None,
        headers: dict[str, str] | None = None,
    ) -> APIError:
        if status is None or headers is None:
            return APIConnectionError(message=message)

        error_map: dict[int, type[APIError]] = {
            400: BadRequestError,
            401: AuthenticationError,
            403: PermissionDeniedError,
            404: NotFoundError,
            409: ConflictError,
            422: UnprocessableEntityError,
            429: RateLimitError,
        }

        error_cls = error_map.get(status)
        if error_cls is not None:
            return error_cls(status=status, body=body, message=message, headers=headers)
        if status >= 500:
            return InternalServerError(status=status, body=body, message=message, headers=headers)
        return APIError(status=status, body=body, message=message, headers=headers)


class APIConnectionError(APIError):
    """Error thrown when a connection to the API cannot be established."""

    def __init__(self, message: str | None = None, cause: BaseException | None = None) -> None:
        super().__init__(status=None, body=None, message=message or "Connection error.")
        self.__cause__ = cause


class APIConnectionTimeoutError(APIConnectionError):
    """Error thrown when a request times out."""

    def __init__(self, message: str | None = None) -> None:
        super().__init__(message=message or "Request timed out.")


class BadRequestError(APIError):
    """400 Bad Request"""
    pass


class AuthenticationError(APIError):
    """401 Unauthorized"""
    pass


class PermissionDeniedError(APIError):
    """403 Forbidden"""
    pass


class NotFoundError(APIError):
    """404 Not Found"""
    pass


class ConflictError(APIError):
    """409 Conflict"""
    pass


class UnprocessableEntityError(APIError):
    """422 Unprocessable Entity"""
    pass


class RateLimitError(APIError):
    """429 Too Many Requests"""
    pass


class InternalServerError(APIError):
    """5xx Internal Server Error"""
    pass
