# Generated by Sterling SDK Generator
# Task Manager API v0.2.0

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional, Union

@dataclass
class Task:
    """"""
    id: str
    title: str
    status: str
    priority: int
    created_at: str
    updated_at: str
    description: Optional[str] = None
    due_date: Optional[str] = None

@dataclass
class TaskListResponse:
    """"""
    tasks: list[Task]
    total: int

@dataclass
class ErrorResponse:
    """"""
    #: Human-readable error message
    error: str
    #: Always false for errors
    success: bool

@dataclass
class CreateTaskRequest:
    """"""
    #: Task title (required)
    title: str
    #: Optional description
    description: Optional[str] = None
    #: Priority (0 = default)
    priority: Optional[int] = None
    due_date: Optional[str] = None

@dataclass
class UpdateTaskRequest:
    """"""
    title: Optional[str] = None
    description: Optional[str] = None
    status: Optional[str] = None
    priority: Optional[int] = None
    due_date: Optional[str] = None


# ── Params types for operations with query parameters ───────────────

@dataclass
class ListTasksParams:
    """Filter by task status"""
    status: Optional[str] = None
    """Maximum number of tasks to return"""
    limit: Optional[int] = None

